name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Hosting Dependencies
        run: npm install
      - name: Build Hosting
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: hosting-build
          path: build
      - name: Install Functions Dependencies
        run: cd functions && npm install
      - name: Build Functions
        run: cd functions && npm run build
      - name: Archive Functions Artifact
        uses: actions/upload-artifact@master
        with:
          name: functions-build
          path: functions/lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Hosting Artifact
        uses: actions/download-artifact@master
        with:
          name: hosting-build
      - name: Download Functions Artifact
        uses: actions/download-artifact@master
        with:
          name: functions-build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
